// Projects — sourced from the 2026 presentation (slides 12, 17–19). Names + clients are real (rule 2).
// Photos for the 11 non-Lopesan projects were auto-mapped from the deck by slide order (image38→Poseidonia …
// image48→Villa Cacique, image22→Plaza Roque) — spot-check pending (CONTENIDO-PENDIENTE).
// Locations are only set where stated in the deck/folder; otherwise a neutral country value + a flag.
// Per-project `scope` is indicative (the deck does not break stages down per project) — flagged.
import { Project } from './types';

import { ov } from './_overrides';
const loc = (es: string, en: string) => ({ es, en });
const RD = loc('República Dominicana', 'Dominican Republic');

const PROJECTS_SEED: Project[] = [
  {
    slug: 'lopesan-costa-bavaro-bloque-f',
    name: 'Lopesan Costa Bávaro — Bloque F',
    client: 'Arenacal PRO',
    sector: 'hotelero',
    location: loc('Bávaro, Punta Cana', 'Bávaro, Punta Cana'),
    status: 'en_ejecucion',
    summary: {
      es: 'Bloque de habitaciones del resort Lopesan Costa Bávaro: estructura de hormigón y encofrado de gran altura ejecutados en obra.',
      en: 'Guest-room block of the Lopesan Costa Bávaro resort: concrete structure and high formwork executed on site.',
    },
    body: {
      es: 'Ejecución de la estructura del Bloque F del resort Lopesan Costa Bávaro, con losas de gran altura, muros monolíticos y apuntalamiento certificado. El alcance incluye el encofrado, el acero de refuerzo y el hormigón de la obra gruesa, coordinados con la ingeniería de encofrado propia de CSD.',
      en: 'Structural execution of Block F of the Lopesan Costa Bávaro resort, with high-rise slabs, monolithic walls and certified shoring. Scope covers formwork, reinforcing steel and the structural concrete, coordinated with CSD’s in-house formwork engineering.',
    },
    scope: ['etapa-03', 'etapa-04', 'etapa-05'],
    cover: { src: 'lopesan/hero', alt: { es: 'Estructura y encofrado de gran altura — Lopesan Costa Bávaro Bloque F', en: 'High structure and formwork — Lopesan Costa Bávaro Block F' } },
    gallery: [
      { src: 'lopesan/estructura', alt: { es: 'Estructura vertical y encofrado de losas', en: 'Vertical structure and slab formwork' } },
      { src: 'lopesan/apuntalamiento', alt: { es: 'Apuntalamiento de losas de gran altura', en: 'Shoring of high-rise slabs' } },
      { src: 'lopesan/losas', alt: { es: 'Losas de hormigón en ejecución', en: 'Concrete slabs under execution' } },
      { src: 'lopesan/encofrado-vertical', alt: { es: 'Encofrado vertical de muros', en: 'Vertical wall formwork' } },
      { src: 'lopesan/puntales', alt: { es: 'Puntales y apuntalamiento en obra', en: 'Props and shoring on site' } },
      { src: 'lopesan/obra', alt: { es: 'Vista general de la obra', en: 'General site view' } },
      { src: 'lopesan/componentes', alt: { es: 'Componentes de encofrado almacenados', en: 'Stored formwork components' } },
      { src: 'lopesan/fachada', alt: { es: 'Avance de fachada del bloque', en: 'Block façade progress' } },
    ],
    featured: true,
    order: 1,
  },
  {
    slug: 'poseidonia',
    name: 'Poseidonia',
    client: 'NOVAL Properties',
    sector: 'hotelero',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Desarrollo hotelero y residencial ejecutado para NOVAL Properties.',
      en: 'Hospitality and residential development delivered for NOVAL Properties.',
    },
    body: {
      es: 'Obra ejecutada por CSD para NOVAL Properties, con alcance de cimentación y estructura. Las fotografías y el detalle del alcance se ampliarán con material adicional del cliente.',
      en: 'Project delivered by CSD for NOVAL Properties, covering foundations and structure. Photography and scope detail will be expanded with additional material from the client.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/poseidonia', alt: { es: 'Vista aérea de la obra — Poseidonia', en: 'Aerial site view — Poseidonia' } },
    gallery: [],
    featured: true,
    order: 2,
  },
  {
    slug: 'hospital-barahona',
    name: 'Hospital Barahona',
    client: 'TORALCO',
    sector: 'hospitalario',
    location: loc('Barahona', 'Barahona'),
    status: 'ejecutado',
    summary: {
      es: 'Infraestructura hospitalaria ejecutada para TORALCO en Barahona.',
      en: 'Healthcare infrastructure delivered for TORALCO in Barahona.',
    },
    body: {
      es: 'Obra civil y estructura para un proyecto hospitalario en Barahona, con las exigencias técnicas y de plazo propias de la infraestructura de salud.',
      en: 'Civil works and structure for a hospital project in Barahona, with the technical and schedule demands typical of healthcare infrastructure.',
    },
    scope: ['etapa-02', 'etapa-03', 'etapa-04'],
    cover: { src: 'projects/hospital-barahona', alt: { es: 'Vista aérea de la obra — Hospital Barahona', en: 'Aerial site view — Hospital Barahona' } },
    gallery: [],
    featured: true,
    order: 3,
  },
  {
    slug: 'brisas-city-center',
    name: 'Brisas City Center',
    client: 'BATCON',
    sector: 'institucional',
    location: loc('Santo Domingo Oeste', 'Santo Domingo Oeste'),
    status: 'ejecutado',
    summary: {
      es: 'Edificación comercial e institucional ejecutada para BATCON en Santo Domingo Oeste.',
      en: 'Commercial and institutional building delivered for BATCON in Santo Domingo Oeste.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/brisas-city-center', alt: { es: 'Obra en ejecución — Brisas City Center', en: 'Project under construction — Brisas City Center' } },
    gallery: [],
    featured: true,
    order: 4,
  },
  {
    slug: 'torre-alpha',
    name: 'Torre Alpha',
    client: 'GV Construcción',
    sector: 'institucional',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Obra ejecutada para GV Construcción.',
      en: 'Project delivered for GV Construcción.',
    },
    scope: ['etapa-02', 'etapa-03', 'etapa-04'],
    cover: { src: 'projects/torre-alpha', alt: { es: 'Cimentación y estructura — Torre Alpha', en: 'Foundations and structure — Torre Alpha' } },
    gallery: [],
    featured: false,
    order: 5,
  },
  {
    slug: 'riviera-bay',
    name: 'Riviera Bay',
    client: 'NOVAL Properties',
    sector: 'hotelero',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Desarrollo hotelero ejecutado para NOVAL Properties.',
      en: 'Hospitality development delivered for NOVAL Properties.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/riviera-bay', alt: { es: 'Estructura del resort — Riviera Bay', en: 'Resort structure — Riviera Bay' } },
    gallery: [],
    featured: false,
    order: 6,
  },
  {
    slug: 'city-place',
    name: 'City Place',
    client: 'Best In Pro',
    sector: 'institucional',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Conjunto ejecutado para Best In Pro.',
      en: 'Complex delivered for Best In Pro.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/city-place', alt: { es: 'Vista aérea del conjunto — City Place', en: 'Aerial view of the complex — City Place' } },
    gallery: [],
    featured: false,
    order: 7,
  },
  {
    slug: 'monterezzo',
    name: 'Monterezzo',
    client: 'Vista Cana',
    sector: 'hotelero',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Desarrollo ejecutado para Vista Cana.',
      en: 'Development delivered for Vista Cana.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/monterezzo', alt: { es: 'Estructuras en ejecución — Monterezzo', en: 'Structures under execution — Monterezzo' } },
    gallery: [],
    featured: false,
    order: 8,
  },
  {
    slug: 'elements-volare',
    name: 'Elements Volare',
    client: 'Bluewave',
    sector: 'hotelero',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Desarrollo ejecutado para Bluewave.',
      en: 'Development delivered for Bluewave.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/elements-volare', alt: { es: 'Vista aérea de la obra — Elements Volare', en: 'Aerial site view — Elements Volare' } },
    gallery: [],
    featured: false,
    order: 9,
  },
  {
    slug: 'olea',
    name: 'Olea',
    client: 'Bluewave',
    sector: 'hotelero',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Desarrollo frente al mar ejecutado para Bluewave.',
      en: 'Beachfront development delivered for Bluewave.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/olea', alt: { es: 'Edificio frente al mar — Olea', en: 'Beachfront building — Olea' } },
    gallery: [],
    featured: false,
    order: 10,
  },
  {
    slug: 'villa-cacique-38',
    name: 'Villa Cacique 38',
    client: 'Accent Group',
    sector: 'residencial',
    location: RD,
    status: 'ejecutado',
    summary: {
      es: 'Obra residencial ejecutada para Accent Group.',
      en: 'Residential project delivered for Accent Group.',
    },
    scope: ['etapa-03', 'etapa-04'],
    cover: { src: 'projects/villa-cacique-38', alt: { es: 'Estructura residencial — Villa Cacique 38', en: 'Residential structure — Villa Cacique 38' } },
    gallery: [],
    featured: false,
    order: 11,
  },
  {
    slug: 'plaza-roque',
    name: 'Plaza Roque',
    client: '', // not stated in the deck — flagged in CONTENIDO-PENDIENTE
    sector: 'institucional',
    location: loc('Punta Cana', 'Punta Cana'),
    status: 'ejecutado',
    summary: {
      es: 'Fachada ACM e interiores livianos en Plaza Roque, Punta Cana.',
      en: 'ACM façade and light interiors at Plaza Roque, Punta Cana.',
    },
    body: {
      es: 'Envolvente de fachada en ACM e interiores livianos para Plaza Roque, en Punta Cana. Ejemplo del alcance de sistemas livianos (etapa 05) dentro del ciclo constructivo de CSD.',
      en: 'ACM façade envelope and light interiors for Plaza Roque, in Punta Cana. An example of the light-systems scope (stage 05) within CSD’s construction cycle.',
    },
    scope: ['etapa-05'],
    cover: { src: 'projects/plaza-roque', alt: { es: 'Fachada ACM de colores — Plaza Roque, Punta Cana', en: 'Colourful ACM façade — Plaza Roque, Punta Cana' } },
    gallery: [],
    featured: false,
    order: 12,
  },
];

export const PROJECTS: Project[] = ov('projects', PROJECTS_SEED);
